config/routes.rb
Rails.application.routes.draw do
  
  get '/myaccount' => "details#show"
  resources :details, except: :show

  devise_for :admins
  devise_for :users
  resources :exams
  get 'users/sign_in' => "users#sign_out", as: :user_root
   get 'home/index' => 'home#index'
  
  resources :home
 devise_scope :user do

  root :to => "devise/sessions#new"

  get 'title/index' => 'title/index'
  
end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

 # def initialize(user)
  
 #   if user
 #       can :manage, :all
  #    else
   #     can :read, :all
   # end 


    def initialize(user)
    
     if user .admin?
      can :manage, :all
       elsif 
      cannot :manage, :all
   
    end
  
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/detail.rb
class Detail < ActiveRecord::Base
 has_attached_file :image, :styles => { :medium => "10x20>", :thumb => "10x20>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :image, :attachment_presence => true
validates_with AttachmentPresenceValidator, :attributes => :image
validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 1.megabytes

validates_attachment :image, :presence => true,
:content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }
 
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




      def after_sign_in_path_for( resource_or_scope)
 	    home_index_path
      end
      def after_sign_out_path_for(resource_or_scope)
         user_root_path

      end 







end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:edit, :update, :destroy]

  respond_to :html, :js

  def index
    if current_user.present?
      @details = current_user.details
       @details = Detail.all
    respond_with(@exams)
   else
      redirect_to '/users/sign_in'
   
    end
  end

  def show
    @detail = Detail.find(1)    
    respond_with(@detail)
  end

  def new
    @detail = Detail.new
    respond_with(@detail)
  end

  def edit
  end

  def create
    @detail = Detail.new(detail_params)
    @detail.save
    respond_with(@detail)
  end

  def update
    @detail.update(detail_params)
    respond_with(@detail)
  end

  def destroy
    @detail.destroy
    respond_with(@detail)
  end

  private
    def set_detail
      @detail = Detail.find(params[:id])
    end

    def detail_params
      params.require(:detail).permit(:name, :sex, :college, :preexam, :image, :user_id)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @exams = Exam.all
    respond_with(@exams)
  end

  def show
    respond_with(@exam)
  end

  def new
    @exam = Exam.new
    respond_with(@exam)
  end

  def edit
  end

  def create
    @exam = Exam.new(exam_params)
    @exam.save
    respond_with(@exam)
  end

  def update
    @exam.update(exam_params)
    respond_with(@exam)
  end

  def destroy
    @exam.destroy
    respond_with(@exam)
  end

  private
    def set_exam
      @exam = Exam.find(params[:id])
    end

    def exam_params
      params.require(:exam).permit(:name, :date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/details/_edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/_form.html.erb
<%= form_for @detail, :url => details_path, :html => { :multipart => true }  do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="modal-body">
 <ul class="errors"></ul>


  <div class="control-group">
  <div class="field">
    <%= f.label :name %><br>
    <div class="controls">
   
     <input name="detail[name]" type="text">
  </div>
  </div>
  </div>
  <div class="control-group">

  <div class="field">
    <%= f.label :sex %><br>
     <div class="controls">
   
     <input name="detail[sex]" type="text">
  </div>
  </div>
  </div>
  
  <div class="control-group">
  <div class="field">
    <%= f.label :college %><br>
     <div class="controls">
    
     <input name="detail[college]" type="text">
  </div>
  </div>
  </div>
  <div class="control-group">
  <div class="field">
    <%= f.label :preexam %><br>
     <div class="controls">
    
     <input name="detail[preexam]" type="text">
  </div>
  </div>
  </div>
  <div class="control-group">
  <div class="field">
    <%= f.label :image %><br>
     <div class="controls">
    
    <%= f.file_field :image %>
  

  </div>
  </div>
  </div>
  <div class="modal-footer">
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  </div>
</div>
<% end %>

app/views/details/create.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @detail.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @detail.sex %>
</p>

<p>
  <strong>College:</strong>
  <%= @detail.college %>
</p>

<p>
  <strong>Preexam:</strong>
  <%= @detail.preexam %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @detail.image.url(:medium) %>
</p>

app/views/details/edit.js.erb
$("#new_details_panel .panel-body").html("<%= escape_javascript(render 'edit') %>")

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Details</h1>
<div class="well">
  <button type="button" class="btn btn-primary" id="new_detail_button">new</button>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th>College</th>
      <th>Preexam</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>

        <td><%= detail.name %></td>
        <td><%= detail.sex %></td>
        <td><%= detail.college %></td>
        <td><%= detail.preexam %></td>
        <td><%= detail.image %></td>
        <td><%= link_to 'Show', detail %></td>
        <td>
        <button type="button" class="btn btn-primary edit_detail_button" data-details="<%= detail.id %>">Edit</button>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div class="panel panel-default" id="new_details_panel">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    
  </div>
</div>

<div class="panel panel-default" id="show_details_panel">
  <div class="panel-heading">Panel heading without title</div>
  <div class="panel-body">
    
  </div>
</div>

app/views/details/new.html.erb
<div class="modal">

<h1>New Detail</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/new.js.erb
$("#new_details_panel .panel-body").html("<%= escape_javascript(render 'form') %>")

app/views/details/show.html.erb
hi

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.date %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exam.date %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/home/index.html.erb
<!--Start Header-->

<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-12 col-sm-2">
			<!-- need to change -->	<a href="index.html">StudentsSpot</a>
			</div>
			<div id="top-panel" class="col-xs-12 col-sm-10">
				<div class="row">
					<div class="col-xs-8 col-sm-4">
						<a href="#" class="show-sidebar">
						  <i class="fa fa-bars"></i>
						</a>
						<div id="search">
							<input type="text" placeholder="search"/>
							<i class="fa fa-search"></i>
						</div>
					</div>
					<div class="col-xs-4 col-sm-8 top-panel-right">
						<ul class="nav navbar-nav pull-right panel-menu">
							<li class="hidden-xs">
								<a href="index.html" class="modal-link">
									<i class="fa fa-bell"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a class="ajax-link" href="ajax/calendar.html">
									<i class="fa fa-calendar"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a href="ajax/page_messages.html" class="ajax-link">
									<i class="fa fa-envelope"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<%if can? :index, @exams %>
							<li class="btn btn-primary btn-xs"><%= link_to "admin", exams_path %></li>		
							<% end %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
										<img src="img/avatar.jpg" class="img-rounded" alt="avatar" />
									</div>
									<i class="fa fa-angle-down pull-right"></i>
									<div class="user-mini pull-right">
										<span class="welcome">Welcome,</span>
										<span>Vignesh</span>
									</div>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Profile</span>
										</a>
									</li>
									<li>
										<a href="ajax/page_messages.html" class="ajax-link">
											<i class="fa fa-envelope"></i>
											<span>Messages</span>
										</a>
									</li>
									<li>
										<a href="ajax/gallery_simple.html" class="ajax-link">
											<i class="fa fa-picture-o"></i>
											<span>Albums</span>
										</a>
									</li>
									<li>
										<a href="ajax/calendar.html" class="ajax-link">
											<i class="fa fa-tasks"></i>
											<span>Tasks</span>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>Settings</span>
										</a>
									</li>
									<li>
										<a>
							<% if user_signed_in? %>
	<li><%= link_to("logout",  destroy_user_session_path, :method=> :delete, class: 'btn btn-primary btn-xs') %></li>
<% else %>
	<li><%= link_to("login", new_user_session_path) %>
<% end %></li>
										</a>
									</li>

								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main" class="container-fluid">
	<div class="row">
		<div id="sidebar-left" class="col-xs-2 col-sm-2">
			<ul class="nav main-menu">
				<li>
					<a href="ajax/dashboard.html" class="active ajax-link">
						<i class="fa fa-dashboard"></i>

						<span class="hidden-xs">My Page</span>
					</a>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-bar-chart-o"></i>
						<span class="hidden-xs">Exam</span>
					</a>
					
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-table"></i>
						 <span class="hidden-xs">Performance</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/tables_simple.html">Simple Tables</a></li>
						<li><a class="ajax-link" href="ajax/tables_datatables.html">Data Tables</a></li>
						<li><a class="ajax-link" href="ajax/tables_beauty.html">Beauty Tables</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-pencil-square-o"></i>
						 <span class="hidden-xs">Friends</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/forms_elements.html">Elements</a></li>
						<li><a class="ajax-link" href="ajax/forms_layouts.html">Layouts</a></li>
						<li><a class="ajax-link" href="ajax/forms_file_uploader.html">File Uploader</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-desktop"></i>
						 <span class="hidden-xs">Notification</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/ui_grid.html">Grid</a></li>
						<li><a class="ajax-link" href="ajax/ui_buttons.html">Buttons</a></li>
						<li><a class="ajax-link" href="ajax/ui_progressbars.html">Progress Bars</a></li>
						<li><a class="ajax-link" href="ajax/ui_jquery-ui.html">Jquery UI</a></li>
						<li><a class="ajax-link" href="ajax/ui_icons.html">Icons</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-list"></i>
						 <span class="hidden-xs">Pages</span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="ajax/page_login.html">Login</a></li>
						<li><a href="ajax/page_register.html">Register</a></li>
						<li><a id="locked-screen" class="submenu" href="ajax/page_locked.html">Locked Screen</a></li>
						<li><a class="ajax-link" href="ajax/page_contacts.html">Contacts</a></li>
						<li><a class="ajax-link" href="ajax/page_feed.html">Feed</a></li>
						<li><a class="ajax-link add-full" href="ajax/page_messages.html">Messages</a></li>
						<li><a class="ajax-link" href="ajax/page_pricing.html">Pricing</a></li>
						<li><a class="ajax-link" href="ajax/page_invoice.html">Invoice</a></li>
						<li><a class="ajax-link" href="ajax/page_search.html">Search Results</a></li>
						<li><a class="ajax-link" href="ajax/page_404.html">Error 404</a></li>
						<li><a href="ajax/page_500.html">Error 500</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-map-marker"></i>
						<span class="hidden-xs">Maps</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/maps.html">OpenStreetMap</a></li>
						<li><a class="ajax-link" href="ajax/map_fullscreen.html">Fullscreen map</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-picture-o"></i>
						 <span class="hidden-xs">Gallery</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/gallery_simple.html">Simple Gallery</a></li>
						<li><a class="ajax-link" href="ajax/gallery_flickr.html">Flickr Gallery</a></li>
					</ul>
				</li>
				
				 <li>
					<a class="ajax-link" href="ajax/calendar.html">
						 <i class="fa fa-calendar"></i>
						 <span class="hidden-xs">Calendar</span>
					</a>
				 </li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-picture-o"></i>
						 <span class="hidden-xs">Multilevel Exam</span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">First level menu</a></li>
						<li><a href="#">First level menu</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-plus-square"></i>
								<span class="hidden-xs">Second level menu group</span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">Second level menu</a></li>
								<li><a href="#">Second level menu</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle">
										<i class="fa fa-plus-square"></i>
										<span class="hidden-xs">Three level menu group</span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="#">Three level menu</a></li>
										<li><a href="#">Three level menu</a></li>
										<li class="dropdown">
											<a href="#" class="dropdown-toggle">
												<i class="fa fa-plus-square"></i>
												<span class="hidden-xs">Four level menu group</span>
											</a>
											<ul class="dropdown-menu">
												<li><a href="#">Four level menu</a></li>
												<li><a href="#">Four level menu</a></li>
												<li class="dropdown">
													<a href="#" class="dropdown-toggle">
														<i class="fa fa-plus-square"></i>
														<span class="hidden-xs">Five level menu group</span>
													</a>
													<ul class="dropdown-menu">
														<li><a href="#">Five level menu</a></li>
														<li><a href="#">Five level menu</a></li>
														<li class="dropdown">
															<a href="#" class="dropdown-toggle">
																<i class="fa fa-plus-square"></i>
																<span class="hidden-xs">Six level menu group</span>
															</a>
															<ul class="dropdown-menu">
																<li><a href="#">Six level menu</a></li>
																<li><a href="#">Six level menu</a></li>
															</ul>
														</li>
													</ul>
												</li>
											</ul>
										</li>
										<li><a href="#">Three level menu</a></li>
									</ul>
								</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</div>
<!--Start Content-->
<!--Start Content-->

    <div class="row-fluid">
	  
	   
                 
                           <div id="dashboard-header">
                            <h3 >HELLO, Vignesh!</h3>
                           </div>
                                 <div class="col-xs-2 col-sm-1 col-sm-offset-1">
                                     <div id="social" class="row">
										<a href="#">
											<i class="fa fa-google-plus"></i>
										</a>
										<a href="#">
											<i class="fa fa-facebook"></i>
										</a>
										<a href="#">
										<i class="fa fa-twitter"></i>
										</a>
										<a href="#">
										<i class="fa fa-linkedin"></i>
										</a>
										<a href="#">
										<i class="fa fa-youtube"></i>
										</a>
									</div>
								</div>
             
                  <div id="dashboard_links" class="col-xs-12 col-sm-2 pull-right">
                     <ul class="nav nav-pills nav-stacked">
                     <li class="active">
                    
                     <a id="new_detail_button" class="tab-link" href="#">Profile</a>
                     </li>

                      <li>
                       <a id="show_detail_button" class="tab-link" href="#">About</a>
                      </li>
                      <li>
                      <a id="graph" class="tab-link" href="#">Friends</a>
                       </li>
                        <li>
                       <a id="servers" class="tab-link" href="#">Favaroutie</a>
                       </li >
                     </ul>
                  </div>

         
           
             <div class="panel panel-default" id="new_details_panel">
                    <div class="panel-body col-xs-12 col-sm-4">
    
                    </div>
              </div>
        </div>

	  </div>
		<!--End Content-->
    </div>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
 	
					
<%= yield %>

</body>
</html>